### ISSUE TITLE
Run u-net.ipynb

### ISSUE THREAD

**Issue by Chaiwj123** [ArkaJU/U-Net-Satellite#12]
hello, I try to train the network using your data provided through google colab.  However, I trained around 4 hours and go through 70 epochs. The error still around 0.3280 and early stopped. Then i tried to predict but get nothing but only black. Any recommendations on how to deal with the problem ?  Please see the attached screenshots. 

![pred_result](https://user-images.githubusercontent.com/44184026/132325351-ef6d0d32-3ebb-4711-8ebd-0c5ea8090c8a.png)
![loss](https://user-images.githubusercontent.com/44184026/132325354-5ca4a529-9116-424a-8c1f-cc6de1752cb2.PNG)
![train_epochs](https://user-images.githubusercontent.com/44184026/132325361-425ee717-7266-48c7-86de-6c463f0a7970.PNG)

**Comment by ArkaJU** [comment]
Sorry for the late response, hope the response given by @reha5762 has worked.

**Comment by phatberstromgg** [comment]
Hello. I tried and met the same results, it's just the black screen. Could you recheck it and help me, thank you so much.
