### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by usmanxia** [ArkaJU/U-Net-Satellite#2]
The dataset link given at the end of the readme (https://people.eecs.berkeley.edu/~tinghuiz/projects/pix2pix/datasets/maps.tar.gz)
has each file with image and network as single image.
Can you please share how the same dataset was used in your code?

Thank you

![2](https://user-images.githubusercontent.com/29237753/66761188-f26cf500-eebc-11e9-8a5a-d3ea0f349e72.jpg)

**Comment by lamia-dachi** [comment]
hello, I have the same issue, did you get any answer ?

**Comment by ArkaJU** [comment]
Sorry for the late reply. As far as I recall, I had read the mask as grayscale and then applied some sort of thresholding. There are readymade datasets available now like https://www.cs.toronto.edu/~vmnih/data/  so you can try them too.

**Comment by ArkaJU** [comment]
You can find the dataset here: https://drive.google.com/drive/folders/1_wBiTCBZ26F_NNpJshw5kwEHyaSeyzFC?usp=sharing

**Comment by lamia-dachi** [comment]
Thank you !
