### ISSUE TITLE
Pridiction on new imagery

### ISSUE THREAD

**Issue by reha5762** [ArkaJU/U-Net-Satellite#29]
"for i, image in enumerate(mask_test):"
1 I  have tested the model it is only puting the available mask in the predicted directory
3. How to apply the model on new imagery and save its mask ?
4. The below line of code "mask_pred = model.predict(img_val, verbose=1)" is supposed to showcase the new mask
5. then why "for i, image in enumerate(mask_test):" on test mask is done for writing in predicted folder ?

**Comment by ArkaJU** [comment]
You are right: `for i, image in enumerate(mask_test)` should have `mask_pred` instead of `mask_test`. The rest of the questions are answered automatically upon this correction. I'll be fixing it in the code, thanks for pointing it out!
